### PR TITLE
Weather and population support

### PR DESCRIPTION
**Pull request by niemal**
Made use of the Wolframalpha API by creating a script for weather and population functions. Script works by default with arguments such as "-w" for weather and "-p" for population, each followed by the search query respectively.

Note: Search query spaces are interpreted as underscores, therefore for something like "Athens Attiki" you would have to execute it like this:
$ python3 weather_and_population.py -w Athens_Attiki

### CODE REVIEW

**Comment by tomkap** [comment]
LGTM but... Python3(!)

**Comment by freestyl3r** [comment]
Thanks, good job.
I made a slight change, so the last part about argument underscores does not apply anymore.
Now you just have to pass it as a single argument (by enclosing it in quotes).
$ python3 weather_and_population.py -w "Athens Attiki"

**Comment by eavgerinos** [comment]
Nice but 2 suggestions:

- Remove the API key from the source code and use an ENV variable. You don't want anyone to use your key.
- urllib is ugly. Why don't you use requests?

**Comment by freestyl3r** [comment]
You are right about the API key. I saw it as well but i didn't think it was a big deal. I fixed it in the latest commit.

Actually he was using requests and i told him to drop it if it's not a big inconvenience, in order to reduce the already big list of dependencies. :|

**Comment by nickraptis** [comment]
requests is not a dependency. It's a blessing.

**Pull request merged**
